/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trungtamtienganh;
import DTO.PhieuDuThiDTO;
import BLL.PhieuDuThiBLL;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win 10
 */
public class PhieuDuThi extends javax.swing.JPanel {

    /**
     * Creates new form PhieuDuThi
     */
    private DefaultTableModel modelPhieuDuThi;
    private List<PhieuDuThiDTO> listPhieuDuThi;

//    private DefaultTableModel modeltour;
//    private List<TourDTO> tour;
    public PhieuDuThi() {
        this.setBounds(0, 0, 844, 620);
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        initComponents();
        modelPhieuDuThi = (DefaultTableModel) tblPhieuDuthi.getModel();
        listPhieuDuThi = new ArrayList<>();
       
        ShowPhieuDuThi();
        
        tblPhieuDuthi.getColumnModel().getColumn(0).setPreferredWidth(150); //set chiều dài cho cột
        tblPhieuDuthi.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblPhieuDuthi.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblPhieuDuthi.getColumnModel().getColumn(3).setPreferredWidth(20);
        tblPhieuDuthi.setRowHeight(20);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer(); //căn giữa cho ô
        centerRenderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        tblPhieuDuthi.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblPhieuDuthi.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblPhieuDuthi.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }

    void ShowPhieuDuThi() {
        listPhieuDuThi = new PhieuDuThiBLL().loadData();
        modelPhieuDuThi.setRowCount(0);
        for (PhieuDuThiDTO phieuDuThi : listPhieuDuThi) {
            modelPhieuDuThi.addRow(new Object[]{
                phieuDuThi.getHoten(), phieuDuThi.getSdt(), phieuDuThi.getTrinhdo(), phieuDuThi.getStt()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        cbTrinhdo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuDuthi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(850, 620));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Họ và tên:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Trình độ:");

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoten.setToolTipText("");
        txtHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenActionPerformed(evt);
            }
        });

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbTrinhdo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbTrinhdo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A2", "B1" }));
        cbTrinhdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrinhdoActionPerformed(evt);
            }
        });

        tblPhieuDuthi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPhieuDuthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Họ và tên", "Số điện thoại", "Trình độ", "Số thứ tự"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhieuDuthi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phiếu dự thi");

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHoten)
                                .addComponent(txtSdt)
                                .addComponent(cbTrinhdo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel4)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHoten)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTrinhdo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrinhdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrinhdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrinhdoActionPerformed

    private void txtHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String hoten = txtHoten.getText();
        String sdt = txtSdt.getText();
        String trinhdo = (String) cbTrinhdo.getSelectedItem();
        PhieuDuThiDTO phieuDuThiDTO = new PhieuDuThiDTO(hoten, sdt, trinhdo);
        PhieuDuThiBLL.addPhieuDuThi(phieuDuThiDTO);
        this.repaint();
        ShowPhieuDuThi();
    }//GEN-LAST:event_btnLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbTrinhdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhieuDuthi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
