/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trungtamtienganh;

import java.awt.Button;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Win 10
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        int x = screenSize.width;
//        int y = screenSize.height - 40;
//        Dimension scale = new Dimension(x, y);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int a = screenSize.width - 948;
        int x1 = screenSize.width / 8;
        this.setBounds(x1, 20, 948, 738);
//        this.setMaximumSize(scale);
        this.setResizable(false);
        this.setTitle("Trung Tam Tieng Anh");
        initComponents();

        btnPhieuDuThi.setBackground(new java.awt.Color(240, 240, 240));
        btnPhongThi.setBackground(new java.awt.Color(240, 240, 240));
        btnXepPhong.setBackground(new java.awt.Color(240, 240, 240));
        btnNhapDiem.setBackground(new java.awt.Color(240, 240, 240));
        btnTraCuu.setBackground(new java.awt.Color(240, 240, 240));
        btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("uschecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPhieuDuThi = new javax.swing.JButton();
        btnPhongThi = new javax.swing.JButton();
        btnXepPhong = new javax.swing.JButton();
        btnNhapDiem = new javax.swing.JButton();
        btnTraCuu = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 237, 142));

        btnPhieuDuThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPhieuDuThi.setText("Phiếu Dự Thi");
        btnPhieuDuThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuDuThiActionPerformed(evt);
            }
        });

        btnPhongThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPhongThi.setText("Phòng Thi");
        btnPhongThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongThiActionPerformed(evt);
            }
        });

        btnXepPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXepPhong.setText("Xếp Phòng");
        btnXepPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXepPhongActionPerformed(evt);
            }
        });

        btnNhapDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNhapDiem.setText("Nhập Điểm");
        btnNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDiemActionPerformed(evt);
            }
        });

        btnTraCuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTraCuu.setText("Tra Cứu");
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLamMoi.setText("Refresh");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhieuDuThi, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnPhongThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXepPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnPhieuDuThi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPhongThi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXepPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 238, 209));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PhieuDuThi phieuDuThi = new PhieuDuThi();
    PhongThi phongThi = new PhongThi();
    XepPhong xepPhong = new XepPhong();
    NhapDiemThi nhapDiem = new NhapDiemThi();
    TraCuu traCuu = new TraCuu();

    private void btnPhieuDuThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuDuThiActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnPhieuDuThi) {
            jPanel2.removeAll();
            jPanel2.add(phieuDuThi);
            jPanel2.repaint();
            phieuDuThi.repaint();
            phieuDuThi.revalidate();
            btnPhieuDuThi.setBackground(new java.awt.Color(0, 206, 209));
            btnPhongThi.setBackground(new java.awt.Color(240, 240, 240));
            btnXepPhong.setBackground(new java.awt.Color(240, 240, 240));
            btnNhapDiem.setBackground(new java.awt.Color(240, 240, 240));
            btnTraCuu.setBackground(new java.awt.Color(240, 240, 240));
            btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
        }
    }//GEN-LAST:event_btnPhieuDuThiActionPerformed

    private void btnPhongThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongThiActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnPhongThi) {
            jPanel2.removeAll();
            jPanel2.add(phongThi);
            jPanel2.repaint();
            phongThi.repaint();
            phongThi.revalidate();
            btnPhieuDuThi.setBackground(new java.awt.Color(240, 240, 240));
            btnPhongThi.setBackground(new java.awt.Color(0, 206, 209));
            btnXepPhong.setBackground(new java.awt.Color(240, 240, 240));
            btnNhapDiem.setBackground(new java.awt.Color(240, 240, 240));
            btnTraCuu.setBackground(new java.awt.Color(240, 240, 240));
            btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
        }
    }//GEN-LAST:event_btnPhongThiActionPerformed

    private void btnXepPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXepPhongActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnXepPhong) {
            jPanel2.removeAll();
            jPanel2.add(xepPhong);
            jPanel2.repaint();
            xepPhong.repaint();
            xepPhong.revalidate();
            btnPhieuDuThi.setBackground(new java.awt.Color(240, 240, 240));
            btnPhongThi.setBackground(new java.awt.Color(240, 240, 240));
            btnXepPhong.setBackground(new java.awt.Color(0, 206, 209));
            btnNhapDiem.setBackground(new java.awt.Color(240, 240, 240));
            btnTraCuu.setBackground(new java.awt.Color(240, 240, 240));
            btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
        }
    }//GEN-LAST:event_btnXepPhongActionPerformed

    private void btnNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDiemActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnNhapDiem) {
            jPanel2.removeAll();
            jPanel2.add(nhapDiem);
            jPanel2.repaint();
            nhapDiem.repaint();
            nhapDiem.revalidate();
            btnPhieuDuThi.setBackground(new java.awt.Color(240, 240, 240));
            btnPhongThi.setBackground(new java.awt.Color(240, 240, 240));
            btnXepPhong.setBackground(new java.awt.Color(240, 240, 240));
            btnNhapDiem.setBackground(new java.awt.Color(0, 206, 209));
            btnTraCuu.setBackground(new java.awt.Color(240, 240, 240));
            btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
        }
    }//GEN-LAST:event_btnNhapDiemActionPerformed

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnTraCuu) {
            jPanel2.removeAll();
            jPanel2.add(traCuu);
            jPanel2.repaint();
            traCuu.repaint();
            traCuu.revalidate();
            btnPhieuDuThi.setBackground(new java.awt.Color(240, 240, 240));
            btnPhongThi.setBackground(new java.awt.Color(240, 240, 240));
            btnXepPhong.setBackground(new java.awt.Color(240, 240, 240));
            btnNhapDiem.setBackground(new java.awt.Color(240, 240, 240));
            btnTraCuu.setBackground(new java.awt.Color(0, 206, 209));
            btnLamMoi.setBackground(new java.awt.Color(240, 240, 240));
        }
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainForm f = new MainForm();
        f.setVisible(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNhapDiem;
    private javax.swing.JButton btnPhieuDuThi;
    private javax.swing.JButton btnPhongThi;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnXepPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
